"""
monsters_database.py
Slavic Horror Engine v2
Database of Slavic mythology creatures with legends and lore
"""

MONSTERS_DB = {
    "Leshy": {
        "description": "Forest spirit, protector of forests. Large humanoid with blue cheeks, superhuman strength, can shapeshift into any person or animal.",
        "behavior": "Protects forest and wildlife. Becomes furious when trees are cut down or habitat harmed. Can create rainstorms when angry.",
        "legends": [
            "Leads travelers astray in the forest, making them walk in circles",
            "Can change size from tall as a tree to small as a blade of grass",
            "Voice echoes through the forest, mimicking sounds to confuse people",
            "If angered, will eat those who harm his forest",
            "Sometimes appears as an old man to test travelers' kindness",
            "Can make trees move to block paths or create mazes",
            "His laugh causes trees to shake and leaves to fall",
            "Sometimes makes deals with woodcutters to spare certain trees",
            "Can imitate any animal sound perfectly",
            "His footsteps don't make any sound on forest floor",
            "Once trapped a hunter in a circle of trees for three days",
            "Can control the wind direction in his forest",
            "Sometimes appears as a wolf to guide lost children home",
            "His blue blood can heal forest plants",
            "Can communicate with all forest animals",
            "Lives in old dry trees like fir and willow, in hollows and stumps",
            "His abode is protected by dense thickets that never freeze",
            "Animals gather there before their death according to superstition",
            "Sometimes appears as one of many diminutive forest spirits",
            "Large forests may be divided into sections, each with its own leshy",
            "In some tales leshy can gather together living in families",
            "A leshy's wife is called leshachikha or a kidnapped maiden",
            "Leshy homes are covered in animal hides and guarded by dogs",
            "Sometimes appears as the forest chief or woodland king",
            "Can move along human roads but has invisible paths in the forest",
            "Active during transitional hours: at night, dawn, noon, or evil hour",
            "Enjoys jesting, revelry, drinking, and playing cards",
            "All phenomena caused by gusts of wind might be Leshy activities",
            "Fallen trees and roofs torn off by hurricane winds associated with leshy weddings",
            "Leshy enjoy hanging and swaying on tree branches, called hangers down",
            "Frequently sits on stumps whittling wood",
            "Acts as shepherd of all woodland creatures with a staff",
            "May gamble animals away in card games to other forest spirits",
            "Often portrayed as patron of bears and wolves",
            "Can manifest as a white wolf - the pack leader",
            "On the night of Ivan Kupala (June 24) multiple leshy were particularly common",
            "On George's Day in Spring shepherds could make agreements with Leshy",
            "Hunters made agreements with Leshy on Easter and Ivan Kupala night",
            "On the night of Agafon the Monk Leshy runs through villages causing mischief",
            "On the Feast of the Cross Leshy drives animals to play cards with them"
        ],
        "habitat": "Deep forests, especially pine forests",
        "powers": ["Shapeshifting", "Forest control", "Voice mimicry", "Superhuman strength"]
    },
    
    "Baba Yaga": {
        "description": "Old witch-like woman, rides in a mortar with a pestle. Lives in a house on chicken legs.",
        "behavior": "Kidnaps and eats children, especially those who wander into her forest. Can be both helpful and harmful depending on the situation.",
        "legends": [
            "Her house can turn around to face visitors or hide from them",
            "She flies through the sky in her mortar, creating storms",
            "Sometimes helps heroes who show courage and respect",
            "Eats those who fail her tests or answer her questions incorrectly",
            "Knows the secrets of the forest and can grant magical items",
            "In Vasilissa the Beautiful tale, she assigns impossible tasks to the heroine",
            "Her hut stands beyond the thrice-nine kingdoms in the thirtieth realm",
            "She can sense the Russian scent of living people",
            "Sometimes appears as one of three Baba Yaga sisters",
            "In some tales she is the guardian of the gateway to the land of the dead",
            "Her nose may stick into the ceiling when she stretches",
            "She may bear the epithet Baba Yaga kostyanaya noga (bony leg)",
            "Sometimes appears with iron teeth in folk tales",
            "In The Kind and Unkind Girls tale she tests two sisters differently",
            "She once demanded to know why Vasilissa was in her forest",
            "Her fence is sometimes made of human bones and skulls",
            "She can transform into different forms to test travelers",
            "Sometimes gives magical items to those who pass her tests",
            "In some versions she helps the hero find the Firebird",
            "She once kept the fire of life in skulls on her fence"
        ],
        "habitat": "Deep forest in a house on chicken legs",
        "powers": ["Flight", "Magic", "Forest knowledge", "House control"]
    },
    
    "Rusalka": {
        "description": "Water spirit, appears as beautiful young woman with long green hair, pale skin, often wearing a floral wreath. Lives in rivers and lakes.",
        "behavior": "Lures men with beauty and singing, then drowns them. Souls of women who died before marriage or drowned.",
        "legends": [
            "Sits on riverbanks combing her long green hair",
            "Her singing is so beautiful it makes people forget everything",
            "Can shapeshift into animals: snakes, wolves, swans, horses",
            "Dances with men until they die of exhaustion",
            "Most dangerous during Green Week (early summer)",
            "According to Vladimir Propp, originally pagan spirits linked with fertility",
            "Originally considered benevolent before 19th century",
            "Came out of water in spring to transfer moisture to fields and nurture crops",
            "In 19th-century versions became unquiet dangerous beings associated with unclean spirits",
            "According to Dmitry Zelenin, souls of women who committed suicide by drowning",
            "Women who drowned due to unhappy marriage or after becoming pregnant with unwanted children",
            "Soul of young woman who died in or near river comes back to haunt that waterway",
            "Not invariably malevolent - allowed to die in peace if death is avenged",
            "Lures young men with looks or voice into depths of waterways",
            "Entangles victims' feet with long hair and submerges them",
            "Body becomes slippery so victim cannot cling to reach surface",
            "Sometimes tickles victims to death while laughing",
            "Can change appearance to match tastes of men about to seduce",
            "Generally represents universal beauty - highly feared yet respected",
            "Always have loose hair linked to tradition of unwedded maidens",
            "Hair can be fair, black, greenish or completely green",
            "Sometimes cannot stand completely out of water",
            "Can climb trees and sing songs in certain periods of the year",
            "Can sit on docks with only feet submerged, combing hair",
            "Can join other rusalki in circle dances in fields",
            "This behaviour limited to certain periods usually summer",
            "The term derives from rusalija from Latin Rosalia as name for Pentecost",
            "Pre-Christian annual traditions associated spirits with this time of year"
        ],
        "habitat": "Rivers, lakes, riverbanks",
        "powers": ["Beauty charm", "Singing", "Shapeshifting", "Water control"]
    },
    
    "Vodyanoy": {
        "description": "Water spirit, appears as old man with long claws, body covered in moss, algae, seaweed, green beard. Sometimes has fish-like skin.",
        "behavior": "Emerges from souls of dead evil people. Lives in underwater lairs. Comes out at night to drag people into water and drown them.",
        "legends": [
            "Lives near water mills, ponds, swamps, and lakes",
            "Can damage dams, water mills, fishing nets when angered",
            "Stores souls of drowned people in pots underwater",
            "Sometimes appears as human but with water dripping from clothes",
            "Fishermen and millers must make sacrifices to appease him",
            "In Russia sometimes called dedushka vodyanoy (Water-Grandfather)",
            "Also called vodyanik or vodnik in different regions",
            "One that dwells in marshlands may be called bolotnyanik",
            "Essentially an evil and vindictive spirit, a bogeyman of sorts",
            "Favorite sport is drowning humans",
            "Anyone bathing after sunset risks being sucked into the water",
            "Bathing on a holy day without making sign of cross is dangerous",
            "Liked especially to live near watermills",
            "Answers to Czech and Slovak vodník, Slovene vodeni mož",
            "Polish equivalent is topielec (Drowner)",
            "Water demons of West and South Slavic lore similar to East Slavic vodyanoy"
        ],
        "habitat": "Deep waters, especially near mills",
        "powers": ["Water control", "Drowning", "Shapeshifting", "Storm creation"]
    },
    
    "Kikimora": {
        "description": "Female house spirit, tiny hunchbacked woman with thimble-sized head. Lives behind stove or in cellar.",
        "behavior": "Causes sleep paralysis by sitting on chest. Harms livestock, breaks dishes, torments sleepers. Makes sounds like nibbling mouse.",
        "legends": [
            "Enters through keyhole at night",
            "Two types: married to Domovoy (forest origin) or married to Leshy (swamp origin)",
            "Swamp version wears clothes made of moss and grass",
            "Leads travelers astray and takes away children",
            "First explanation for sleep paralysis in Russian culture",
            "Term may originate from Udmurt word for scarecrow",
            "Reflects dual nature as both protector and harbinger of misfortune",
            "Spinning, needlework, and chickens were province of kikimora",
            "If another Kikimora introduced to house original will be angered",
            "Second Kikimora very difficult to get rid of",
            "To appease angry Kikimora, all pots and pans should be washed with fern tea",
            "Sometimes considered wife of Domovoy",
            "Causes sleep paralysis by sitting on victim's chest",
            "Makes sounds like nibbling mouse",
            "Harms livestock and breaks dishes",
            "Torments sleepers at night",
            "Often blamed for household mishaps and bad luck"
        ],
        "habitat": "Behind stove, cellar, keyholes",
        "powers": ["Sleep paralysis", "Household chaos", "Sound mimicry"]
    },
    
    "Domovoy": {
        "description": "Household spirit, appears as small old man who hides in basement or attic. Protector of household.",
        "behavior": "Protects household if treated well, curses family if angered. Brings good fortune or misfortune depending on relationship.",
        "legends": [
            "Lives near oven, under doorstep, in hearth",
            "Term comes from Indo-European root dom shared by words for abode",
            "Compared to Roman Di Penates, genii of the family",
            "Believed to protect well-being of kin in any aspect",
            "Very protective towards children and animals, constantly looking after them",
            "Often represented as fighting with one another to protect kin",
            "Winner's Domovoy takes possession of vanquished rival's household",
            "Shares joys and sorrows of the family",
            "Can forebode and warn about future events like death, plagues, wars",
            "Becomes angry if family corrupted by bad behavior and language",
            "May even quit and leave kin unprotected against illness and calamity",
            "Usually represented as old grey-haired man with flashing eyes",
            "May manifest in form of animals like cats, dogs or bears",
            "Also appears as master of house or departed ancestor of family",
            "Sometimes provided with tail and little horns",
            "In some traditions symbolized as snakes",
            "Household gods represented as statuettes made of clay or stone",
            "Placed in niches near house's door or on mantelpieces above ovens",
            "Sacrifices practiced to make him participate in family life",
            "Offering of evening meal left for him",
            "In cases of great anger, sacrifice of a cock at midnight",
            "Sprinkling nooks and corners with animal's blood",
            "Slice of bread strewn with salt wrapped in white cloth offered",
            "Family bows towards four directions reciting prayers to Domovoy",
            "Connected with house building itself",
            "Sacrifices practiced when family moved to newly built house",
            "Hen and first slice of bread offered and buried in courtyard",
            "Reciting formula to invite god to inhabit new house",
            "Similar rituals to invite Domovoy to transfer between houses"
        ],
        "habitat": "Hearth, basement, attic, under doorstep",
        "powers": ["Household protection", "Wealth manipulation", "Fortune control"]
    },
    
    "Likho": {
        "description": "Embodiment of evil fate and misfortune. One-eyed creature, often depicted as old skinny woman in black or evil male goblin.",
        "behavior": "Personification of bad luck. Clings to neck, rides on back. Cannot be escaped once attached.",
        "legends": [
            "Person who finds Likho must cut off hand to escape",
            "Can ride on person's neck, victim drowns trying to escape",
            "Passed from person to person with gifts",
            "Comes to eat people, used to scare children",
            "Proverbs warn: 'Don't wake likho while it's quiet'",
            "Several basic versions of tales about how a person meets with Likho",
            "A person eventually cheats Likho",
            "A person cheats Likho, runs away, sees valuable thing, grabs it out of greed",
            "Hand sticks to valuable thing, person has to cut off hand to escape",
            "Likho cheats a person and rides on their neck",
            "Person wanting to drown Likho jumps into river and drowns themself",
            "Likho floats out to chase other victims",
            "Likho is received or passed to another person with a gift",
            "Within superstitions, Likho was supposed to come and eat a person",
            "Used to scare small children in Ukrainian folklore",
            "Sometimes portrayed as type of bad spirit that can cling to one's neck",
            "Most-known legend: smith recalls life, realizes never had misfortune",
            "Smith decides to find misfortune himself, meets tailor who also never saw misfortune",
            "They find hut with thin old one-eyed woman who welcomes them",
            "She shoves tailor into furnace and eats him, smith has to escape",
            "Smith boasts he can forge anything, she asks for second eye",
            "Instead of giving second eye, he destroys her only eye and tries to escape",
            "Still gets caught by Likho, returns home with only one arm",
            "Tells others he did meet misfortune now",
            "Absurd scenario shows misfortune is more devastating than one might think"
        ],
        "habitat": "Anywhere misfortune exists",
        "powers": ["Misfortune manifestation", "Attachment", "Curse spreading"]
    },
    
    "Poludnitsa": {
        "description": "Lady Midday, noon spirit. Beautiful woman in white dress, sometimes appears as old hag or terrifying crone.",
        "behavior": "Punishes those who work in fields at midday. Causes heatstroke, strikes with scythe, asks riddles with deadly consequences.",
        "legends": [
            "Appears in fields during harvest at noon",
            "Attacks workers who don't rest during midday heat",
            "Can cause heatstroke or madness",
            "Asks riddles - wrong answer means death",
            "Represents dangers of excessive labor in summer heat",
            "Name comes from poludne, Slavic word for noon",
            "Called Poludnitsa in Russian, Południca in Polish, Polednice in Czech",
            "Usually pictured as young woman dressed in white roaming field bounds",
            "Assails folk working at noon causing heatstrokes and aches in neck",
            "Sometimes causes madness",
            "Takes form of whirling dust clouds and carries scythe, sickle or shears",
            "Will stop people in field to ask difficult questions or engage in conversation",
            "If anyone fails to answer or tries to change subject, cuts off head or strikes with illness",
            "May appear as old hag, beautiful woman, or 12-year-old girl",
            "Useful in scaring children away from valuable crops",
            "Only seen on hottest part of day, personification of sun-stroke",
            "According to northern Russian regions, has giant frying pan in hands",
            "Blocks rye from scorching sun's rays or burns rye with herbs during flowering",
            "May appear at midnight and show person how to find flower that makes them invisible",
            "According to beliefs, loves to dance",
            "If she sees girl lying down to rest in field, wakes her and persuades her to dance",
            "Girl forced to dance until evening's dawn",
            "Poludnitsa cannot be beaten in dancing",
            "If girl beats her, noon spirit presents her with rich dowry",
            "Between 11 AM and 1 PM you did not work in open field",
            "Reason was not heat but that Poludnitsa was walking",
            "If she found you in wheat she would put a question to you",
            "If you could not answer she would twist your head until neck broke",
            "Or strike with sunstroke, or lead in circles until village found you next morning",
            "Czech Polednice version: tall thin woman in white who walks into cottage at noon",
            "Takes screaming child that mother threatened her with",
            "Mother used demon's name to frighten child, demon heard and came",
            "Question game is most particular detail in tradition",
            "Polish folklorist Jan Karłowicz collected several variants in 1890s",
            "In one version asks harvester to name every plant in field in order of usefulness",
            "Harvester who answered correctly rewarded with gift of grain",
            "Harvester who failed found at sunset with neck broken",
            "Another variant: asks woman spinning flax to recite entire process of flax cultivation",
            "Woman who could do it lived, who could not was struck dumb for rest of life",
            "Demon tests whether you actually know your work",
            "Village where older women taught younger ones full procedure had no fear of her"
        ],
        "habitat": "Agricultural fields at noon",
        "powers": ["Heat control", "Riddles", "Scythe attacks", "Madness induction"]
    },
    
    "Bannik": {
        "description": "Bathhouse spirit, small naked old man with long beard, body covered in birch leaves from bath brooms. Shapeshifter.",
        "behavior": "Can be benevolent or malevolent. Snatches unattended babies. Scratches with claws - unseen scratch means great misfortune.",
        "legends": [
            "Lives in bathhouse (banya), can appear as stone or coal in oven",
            "Can predict future through steam patterns",
            "May appear as local person to those who stumble across him",
            "Bathhouse was place of birth, making Bannik important",
            "Scratches bring misfortune if you don't see them happen",
            "Tutelary deity of private or public bathhouses",
            "Corresponds to Komi Pyvsiansa",
            "Slavic bathhouses were like saunas",
            "Place where women could give birth",
            "Also place for divination endowed with vital forces",
            "Most dangerous and malicious of home spirits",
            "Can appear as stone or coal in oven",
            "Predicts future through steam patterns",
            "May appear as local person to those who stumble across him"
        ],
        "habitat": "Bathhouses (banya)",
        "powers": ["Shapeshifting", "Future prediction", "Fortune telling", "Curse scratching"]
    },
    
    "Upyr": {
        "description": "Original vampire, prototype of Western vampire. Not aristocratic, wears burial clothes. Extremely violent, sucks blood with all teeth.",
        "legends": [
            "Created from people cursed before death or sudden death",
            "Can roam in daylight, prefers night attacks",
            "Rips victim's throat, sometimes mutilates bodies",
            "Killed by stake through heart and cutting off head",
            "Souls of violent death, sorcerers, unchristened children",
            "Also witches, unchristened children, those killed by another upyr",
            "Opposite to most vampire beliefs, commonly thought to roam in bright daylight",
            "Physically different people were potential upyr candidates: redheads, left-handed",
            "Those with limp, unibrow, double set of teeth, gray mark on back",
            "Religiously other like Lutherans in Catholic communities",
            "Suspicious traits included walking by moonlight, having big head",
            "No armpit or pubic hair also suspicious",
            "Often described as having two hearts and two souls like strzygas",
            "Women who died during or after childbirth particularly vulnerable",
            "Feared they would return to orphaned child as upyrs to feed at night",
            "In Silesia those who died in childbirth buried near cemetery wall",
            "Lack of rigor mortis, flushed face or blood beneath nails were signs",
            "Signs of misdeeds: fatigue, pallor, sweating, recurring nightmares",
            "Could haunt family if family burned photograph of deceased",
            "Dead person buried in old shirt could also become upyr",
            "Recognized by having innocent child ride horse to cemetery",
            "Child would indicate grave of upyr",
            "Could be seen in mirror in evening",
            "In Sieradz region people would not look into mirrors after dusk",
            "Arrived at night carrying heads in arms",
            "If head not detached, had glowing wolf-like eyes",
            "Some caused menace during daytime climbing bell towers",
            "Killed everyone who heard their shriek",
            "Drank human blood, used superhuman strength to tear victims to shreds",
            "Could also kill with breath or shrieks",
            "Harassed people at night making them suffocate or sleepwalk",
            "Husbands and wives became upyrs visiting widowed spouse after death",
            "Would do chores they did during lifetime",
            "Sometimes harassed the family",
            "Cattle and human plagues often blamed on witches or upyrs",
            "Dead should be taken out through special exit to prevent becoming upyr",
            "Garlic heads, bricks, iron chunks placed in mouths before burial",
            "Branches of wild rose, hawthorn, blackthorn put in coffins",
            "Coffins sprinkled with poppy-seed to occupy upyrs",
            "Vampire burial: head cut off and put between legs of corpse",
            "Corpse could be burned, nailed to coffin, or repositioned face-down",
            "Remedy to stop upyr returning to grave - at dawn disappears or changes to black tar",
            "Protective measure: drink upyr's blood or eat soil off its grave"
        ],
        "habitat": "Graves, attacks at night",
        "powers": ["Blood drinking", "Violence", "Daylight walking", "Undead strength"]
    },
    
    "Viy": {
        "description": "High-ranking demonic figure from Underworld. Monstrous humanoid, tall and broad-shouldered. Heavy iron eyelids - gaze brings death.",
        "behavior": "Lord of dark powers. His gaze is lethal - eyelids too heavy to lift alone, requires helpers. Once sees victim, they die.",
        "legends": [
            "Eyelids so heavy he cannot lift them himself",
            "Requires minions to lift his eyelids",
            "His gaze brings instant death to anyone he sees",
            "Appears from underworld when summoned by dark magic",
            "Cannot be killed once his gaze falls upon you",
            "Once killed three seminary students who couldn't escape his gaze",
            "His touch turns flesh to ash",
            "Can summon lesser demons with a single word",
            "His iron eyelids are forged in the deepest hell",
            "Once stayed on earth for three nights causing terror",
            "Cannot look upon holy ground or sacred objects",
            "His presence makes all lights dim and flicker",
            "Can only be summoned by those who have sold their soul",
            "Once destroyed a church just by looking at it",
            "His voice causes earthquakes when he speaks",
            "Character from Nikolai Gogol's horror novella Viy published in 1835",
            "Gogol claimed Viy was taken from Ukrainian folklore",
            "Some modern researchers claim Viy is author's own invention",
            "Folkloric data shows demonic characters with similar appearance in Ukrainian lore",
            "Demonic characters with heavy eyelids that need lifting appear in Ukrainian folk tales",
            "Story tells of Khoma Brut student at monastery in Kyiv",
            "Khoma takes shelter at house of older woman who snatches him to fly through night sky",
            "Realizing caught by witch Khoma struggles free and takes revenge",
            "Witch transforms into most beautiful girl Khoma ever seen",
            "Khoma summoned to read psalms over dying Cossack chief's daughter",
            "Daughter is the witch Khoma beat to death",
            "Vigil held in neglected chapel for three nights",
            "Each night cadaver rises assailing Khoma with host of imps and night creatures",
            "Protected by Khoma's psalm recitations behind protective circle",
            "On third night witch summons Viy because only one who can see through circle",
            "Squat Viy hairy with iron face bespattered with black earth",
            "Limbs like fibrous roots",
            "Viy orders Raise my eyelids I cannot see",
            "Points out where young man is spirits all attack Khoma falls dead",
            "Gogol's author note: Viy is colossal creation of folk imagination",
            "Name applied by Little Russians to chief of gnomes whose eyelids reach to ground",
            "Some scholars believe concept based on Saint Cassian the Unmerciful",
            "Saint Cassian said to have eyebrows descending to knees raised only on Leap Year"
        ],
        "habitat": "Underworld, summoned by dark rituals",
        "powers": ["Death gaze", "Underworld authority", "Demonic summoning"]
    },
    
    "Koschei": {
        "description": "Deathless sorcerer, skeletal appearance. His soul is separated from body and hidden on faraway island.",
        "behavior": "Immortal but not invincible. Soul hidden in nested containers: needle in egg, egg in duck, duck in hare, hare in chest, chest on oak on island.",
        "legends": [
            "Soul hidden in needle inside egg inside duck inside hare inside chest on oak on magical island",
            "Cannot die while his soul remains hidden",
            "Kidnaps princesses, especially Marya Morevna",
            "In Marya Morevna tale, he was chained in a dungeon and freed by Ivan Tsarevich",
            "After drinking twelve buckets of water, his magic powers returned and he broke his chains",
            "He abducted Marya Morevna while she was going to war",
            "Ivan Tsarevich pursued him three times, each time Koschei killed him",
            "Koschei cut Ivan into pieces and put him in a barrel thrown into the sea",
            "Ivan was revived by his sisters' husbands - wizards who transform into birds",
            "Koschei has a magic horse that can catch anyone even after doing many tasks first",
            "Ivan had to get a magic horse from Baba Yaga to defeat Koschei",
            "Beyond the thrice-nine kingdoms in the thirtieth realm lives Baba Yaga with magical mares",
            "Koschei served Baba Yaga as a herdsman for three days to get his magic horse",
            "Sometimes appears with tusks or fangs in different tales",
            "May ride a three-legged or seven-legged horse in various versions",
            "Can cast a sleep spell that can be broken by playing an enchanted gusli",
            "Sometimes has eyelids so heavy he requires servants to lift them",
            "His name may derive from the Turkic word for slave or captive",
            "Some scholars connect him to the Polovtsian leader Khan Konchak from 12th century",
            "In some tales he appears as Tsar Koschei, ruler of all sorcerers"
        ],
        "habitat": "Magical island, dark fortress",
        "powers": ["Immortality", "Dark magic", "Soul separation", "Kidnapping"]
    },
    
    "Zmey Gorynych": {
        "description": "Slavic dragon with multiple heads (3-12). Body covered in red or green scales, iron claws. Speaks human language.",
        "behavior": "Lives on high mountains or deep in forests. Can shapeshift into handsome young man to trick people. Steals young girls as brides.",
        "legends": [
            "Slain by bogatyr Dobrynya Nikitich in famous bylina",
            "Multiple heads, each can breathe fire independently",
            "Can transform into human to deceive enemies",
            "Name means 'Dragon, Son of Mountain'",
            "In Dobrynya Nikitich bylina, he had twelve trunks (heads)",
            "Dobrynya encountered him while bathing unarmed in the Puchai River",
            "Dobrynya used a hat of the Greek land to defeat the dragon",
            "The dragon pleaded for mercy and made a nonaggression pact",
            "He broke the promise and flew to Kiev, abducting Zabava Putyatishna",
            "Zabava was the niece of Prince Vladimir",
            "Dobrynya fought the dragon at the Saracen Mountains for three days",
            "On the third day a voice from Heaven told him to fight three more hours",
            "Dobrynya eventually killed the dragon in three hours",
            "The dragon's blood did not seep into the ground for three days",
            "Dobrynya wallowed in the pool of blood for three days",
            "A voice from Heaven told him to stick his spear in the ground with an incantation",
            "The blood was then swallowed by the earth and Zabava was rescued",
            "The dragon raised pups in caves of the Saracen Mountains",
            "One of the pups bit Dobrynya's horse leg and immobilized it",
            "Dobrynya used a magic Shemakhan whip to restore his horse's vigor",
            "The dragon kept hostages in his lair",
            "In some variants the dragon is female and called Zmei Gorynishche",
            "The battle follows a pattern of threes: three heads, three days, three days in blood",
            "Cut off a head and it grows back unless the stump is seared with fire",
            "The hero wins by endurance not strength alone",
            "Sometimes appears as Tugarin Zmeevich, a man-like dragon",
            "Tugarin faces off against bogatyr Alyosha Popovich and is slain"
        ],
        "habitat": "High mountains, deep forests",
        "powers": ["Fire breathing", "Shapeshifting", "Human speech", "Flight"]
    },
    
    "Azhdaya": {
        "description": "Demonic dragon, odd number of heads (never even). Spits fire, terrible roar, evil appearance. Lives in mountain caves.",
        "behavior": "Comes out when hungry, flies down to villages to snatch cattle and harm villagers. Causes eruptions and hailstorms.",
        "legends": [
            "Demonic version of dragon, over 100 years old",
            "Odd number of heads - never even",
            "Lives in caves high in mountains",
            "When flies down, causes destruction and fear",
            "Name derived from Persian 'azhdahā' meaning dragon",
            "Etymologically derives from Persian Aždahā meaning dragon or serpent",
            "Entered Slavic lexicon through contact with Ottoman Empire and Persian traditions",
            "Image evolved from symbol of raw elemental power to representation of demonic evil",
            "In Serbia Bosnia and Montenegro known as monstrous adversary slain by Saint George",
            "Saint George's victory symbolizes triumph of divine light over infernal darkness",
            "Appearance varies but core traits consistent: massive serpentine body thick scales",
            "Odd number of heads often three five or seven",
            "Each head could spew fire independently",
            "So enormous could encircle mountains or block rivers with body",
            "Under different names in Slavic regions: Aždaja in Serbian and Bosnian",
            "Sometimes equated with Ala or Hala in Bulgarian",
            "Similar to Azdeha in Albanian oral tradition",
            "All share linguistic root in Persian Aždahā",
            "Distinct from Zmaj which can be ambivalent",
            "Azhdaya purely destructive exists only to consume conquer and corrupt",
            "Powers vast and terrifying: fly across skies breathe fire hot enough to melt iron",
            "Cause storms that tear through villages",
            "Blamed for natural disasters volcanic eruptions droughts",
            "Dwell deep underground or within mountain caverns",
            "Guard immense treasures or entrances to other worlds",
            "Only saints or divinely chosen heroes capable of defeating such beast"
        ],
        "habitat": "Mountain caves",
        "powers": ["Fire breathing", "Destructive roar", "Flight", "Weather control"]
    },
    
    "Chort": {
        "description": "Demon with goat hooves, horns, tail. Anthropomorphic, similar to early Christian Devil. Can be both good and bad.",
        "behavior": "Sometimes brings misery and misfortune, sometimes befriends heroes and gives magical items. Makes deals at crossroads.",
        "legends": [
            "Son of Slavic god Chernobog and goddess Mara",
            "Makes deals with humans at crossroads (older than Faust legend)",
            "Can be helpful spirit or demonic destroyer",
            "Represents both chaos and justice",
            "Trickster figure in many folk tales",
            "Anthropomorphic malign spirit or demon in Slavic folk tradition",
            "Often depicted identically to Christian devils with horns hooves and skinny tail",
            "Sometimes identified as son of god Chernobog and goddess Mara",
            "In folk Christianity considered lesser minions of Satan",
            "Word descends from Proto-Slavic čьrtъ meaning devil or demon",
            "Etymologically associated with Slavic curses about hell",
            "Universal to all Slavic ethnicities",
            "Commonly depicted as devil with all features horns tail hooves and sometimes one short leg",
            "More of a metaphor spiritual allegory embodying darkness and fear of unknown death",
            "Originally god of destiny who also brought death according to Afanasyev",
            "Naturally people began viewing it as embodiment of evil or devil",
            "Czech view Chert as character trying to trick people into selling their souls",
            "If they fall for it they go straight to hell",
            "If Chort loses the bet the person gets their soul back",
            "Neither hero nor villain nature at least dual",
            "Encompasses ideas of dark spirits and malign souls but also positive ones like faith destiny and justice",
            "Creature of darkness often depicted as monstrous and grotesque entity",
            "Embodies antithesis of all that is good and pure",
            "Often portrayed as trickster playing pranks on humans and causing mischief",
            "Pranks range from minor annoyances like stealing milk from farmers to more sinister acts",
            "Leads people astray in forest or causes storms and plagues",
            "Malevolent force actively tempting humans and seeking to corrupt their souls",
            "Main goal to lure individuals away from their faith and morality",
            "Leads them down path of sin and ultimately to damnation",
            "Often seen as counterpart to other creatures like witches vampires and other demons",
            "Might collaborate or compete for power with other supernatural beings",
            "Famous tale The Chort and the Peasant where cunning peasant outsmarts Chort",
            "Chort offers deal if peasant can outsmart him in riddle contest receives vast fortune",
            "If peasant fails Chort will take his soul",
            "Chort confident in cunning poses riddle about human life stages",
            "Peasant answers correctly stunning Chort",
            "Chort steals the actual moon from actual sky and stuffs it into his pocket like stolen apple",
            "Motive is petty revenge against village blacksmith",
            "Found on territories considered spiritually unclean",
            "Most often cemeteries swamps abandoned places crossroads bridges",
            "Places of person's violent death or execution",
            "Depicted with fur snout tail horns animal-like backwards knees hooves or bird feet",
            "Usually described as chicken or stork feet and claws",
            "Eyes and tongue said to be of hellish colour",
            "Often hide inhuman features under clothing",
            "In Ukrainian folklore Chort acts as generalized concept for unclean forces",
            "Can substitute for wide variety of demonic beings",
            "Despite significant influence of folk-christian worldviews several features traced to archaic Slavic demonology",
            "Associated with ideas about afterlife and zoolatric beliefs",
            "Common perception of demons in Ukrainian folklore is casual and down-to-earth",
            "Chort primarily characterized as failed demon more than evil one",
            "Has developed imagination but deprived of ability to use it effectively",
            "Credited with creating things villagers consider negative: vodka tobacco cliffs ravines",
            "In some legends credited for creation of horses too",
            "Allows horses to sense when evil spirits are nearby",
            "Originally Draughtsman of Fate supernatural being who drew lines of human destiny in earth",
            "Folklorist Alexander Afanasyev concluded chort was originally god of destiny who also brought death",
            "Only later after missionaries came after baptisms and Christianization did this god of fate get demoted",
            "His position in cosmic order erased",
            "What remained was shape hooves horns tail sulfur",
            "Folk memory was not so easily overwritten",
            "Slavic peasant never quite believed Chort was pure evil",
            "Stories kept something of old ambiguity alive",
            "Creature who could be tricked bargained with outwitted even pitied",
            "Pre-Christian trickster spirit survived inside Christian costume grinning through mask"
        ],
        "habitat": "Crossroads, underworld, anywhere deals are made",
        "powers": ["Deal making", "Magic granting", "Chaos creation", "Shape shifting"]
    },
    
    "Drekavac": {
        "description": "Demonic creature from dead unbaptized babies. Small, hairy with long fur and claws. Attacks with loud shriek like baby in pain.",
        "behavior": "Lives in graveyards, areas where it died. Jumps on backs at night, forces people to run. Attacks face with claws if resisted.",
        "legends": [
            "Created from souls of unbaptized babies",
            "Afraid of light and dogs",
            "Shriek resembles crying baby in pain",
            "Forces victims to run until exhausted",
            "Flees screaming when confronted with light",
            "Literally the screamer or the screecher",
            "Also called drekalo krekavac zdrekavac or zrikavac",
            "Name derived from verb drečati meaning to screech",
            "Mythical creature in South Slavic mythology",
            "Often used to scare Slavic children",
            "Does not seem overly aggressive but more serve as warning or prophecy",
            "Some tales of drekavac jumping on people's backs and trying to drown them or otherwise kill them",
            "Screaming undead creature from South Slavic folklore",
            "Found across Serbia Bosnia Croatia and wider Balkans",
            "If shadow of drekavac falls across person that person will sicken and die",
            "Keeps to night and at its boldest during twelve days between Christmas",
            "Likes to drown people and animals who happen to walk close to their watery lair at late night",
            "During 1900s locals reported sightings on shores of Sava river in region of Syrmia",
            "Other names include Drek Drekalo Krekavac Zdrakavac Zdrekavac Zrikavac Cviljek Kukac and Vriskavac",
            "Restless spirit that cannot pass on becomes more malevolent or demonic",
            "Often used to frighten children into behaving",
            "Terrifying scream that can be heard from great distance",
            "Appears most often during dark winter nights",
            "Considered harbinger of death and misfortune"
        ],
        "habitat": "Graveyards, places of infant death",
        "powers": ["Baby shriek", "Back jumping", "Claw attacks", "Night ambush"]
    },
    
    "Bolotnik": {
        "description": "Water monster, looks like old man with big frog-like eyes, green beard, long hair. Body covered in moss, seaweed, fish scales.",
        "behavior": "Lures people into water by making duck sounds. Grabs limbs and drags to death. Found anywhere near water bodies.",
        "legends": [
            "Makes sounds like duck to attract victims",
            "Unlike Vodyanoy, has no fixed lair",
            "Can appear near any body of water",
            "Frog-like appearance with green beard",
            "Drags victims underwater to drown them",
            "Male swamp spirit from Slavic mythology",
            "Usually portrayed as man or old man with big frog-like eyes",
            "Green beard and long hair",
            "Body covered with dirt algae and fish scales",
            "Legends from Vitebsk Governorate described as dirty fat eyeless creature",
            "Motionlessly sits at bottom of swamp",
            "Some accounts say has long arms and tail",
            "Like majority of Slavic water spirits lures and drags people into water",
            "Believed to have neither wife nor children",
            "Other legends say married to bolotnitsa female swamp spirit",
            "Rarely found in folklore",
            "Often thought of as kind of vodyanoy leshy or chort",
            "Image of bolotnitsa mixed with rusalka vodyaniha leshachikha wild hag swamp kikimora",
            "Many names: bolotny bolotny dedko bolotny chort bolotny leshy tsar bolotny",
            "Also called antsybal antsybul antsybalka antsybalit anchibal anchibol",
            "Origin same as other evil spirits: fallen angels thrown down from heaven by God",
            "Or creations of Satan",
            "Novgorod Kormchaia Book of 13th century mentions Eastern pagan Slavs made sacrifices to swamps",
            "In Russian North bolotnitsa is mistress of swamp and tundra",
            "Also known as bolotnaya baba lopatnitsa omutnitsa"
        ],
        "habitat": "Near any water bodies",
        "powers": ["Duck mimicry", "Drowning", "Water camouflage", "Limb grabbing"]
    },
    
    "Aspid": {
        "description": "Dragon with bird-like features, one head, beak, very long neck. Smaller than Azhdaya but more bird-like.",
        "behavior": "Prefers solitude in mountains. Rarely comes down, when does spits fire and destroys everything in path.",
        "legends": [
            "Bird-like dragon with beak and long neck",
            "Lives in mountains, prefers solitude",
            "When descends, burns and ravages whole villages",
            "More avian features than other dragons",
            "Destructive when angered or hungry",
            "Winged snake with bird-like features according to Slavic mythology",
            "Suffers from lack of primary sources about the creature",
            "Few tales remain and some are conflicting",
            "Main conflict is what form Aspid takes: dragon with elements of bird or snake",
            "In first case pictured with beak and some feathers upon scales",
            "Creates odd mix of reptile and avian",
            "Second form replaces beak with snake's head",
            "Regardless of form similarities in rest of description",
            "Precious stones often built into wings and/or hide",
            "Sometimes two heads each which could breathe fire",
            "Remote nature preferring to keep to mountains",
            "When Aspid descended destruction could be widespread",
            "Story of snake permeates through many tales in pagan societies",
            "May be post-Christianization change turning appearance into Devil's snake",
            "Similar to Weles/Veles who appears as snake in battle against Perun",
            "According to Russian legend Aspid is monstrous winged snake",
            "Has bird's nose and two trunks",
            "Wings pested and burn-perelivayutsya like precious stones",
            "By some tales monstrosity unpreglyadno chern",
            "From this expression aspidno-cherny color",
            "Where Aspid flies those places devastated",
            "Lives in stone mountains or on gloomy severe forested north",
            "Never sits on earth only on stone",
            "Impossible to kill with arrow can only burn",
            "Reminds of Zmey Gorynych from Russian tales and basilisk",
            "Also reminds of Ekhidna deva snake-headed who bore three progenitors of Scythian tribes"
        ],
        "habitat": "Mountains",
        "powers": ["Fire breathing", "Flight", "Destruction", "Mountain dwelling"]
    },
    
    "Bukavac": {
        "description": "Six-legged water creature with slime-covered skin, big curvy horns, big mouth, very long tail. Southern Slavic version of Vodyanoy.",
        "behavior": "Lives near swamps, lakes, rivers, ponds. Has lair, drags people into water like Vodyanoy.",
        "legends": [
            "Six legs unlike other water spirits",
            "Skin covered in slime",
            "Big curvy horns and long tail",
            "Origin similar to Drekavac (unbaptized babies)",
            "Lives in lair like Vodyanoy",
            "Southern Slavic water spirit similar to Vodyanoy",
            "Lives near swamps lakes rivers ponds",
            "Has lair unlike Vodyanoy who is more mobile",
            "Drags people into water to drown them",
            "Makes loud booming sounds that can be heard from far away",
            "Often described as more monstrous than Vodyanoy",
            "Specific to Southern Slavic folklore traditions"
        ],
        "habitat": "Swamps, lakes, rivers, ponds",
        "powers": ["Drowning", "Water dwelling", "Multi-legged swimming", "Horn attacks"]
    },
    
    "Strzyga": {
        "description": "Female demonic creature similar to vampire. People born with two hearts, two souls, sometimes two sets of teeth become strzygas.",
        "behavior": "Chased from village if identified. Sometimes buried alive. Comes back from grave, appears as owl, attacks travelers.",
        "legends": [
            "Born with two hearts and two souls",
            "Sometimes has two sets of teeth",
            "Takes appearance of owl at night",
            "Sucks blood and sometimes eats insides",
            "Prevented by burning body or piercing with nails",
            "Polish female demonic creature similar to vampire",
            "People born with two hearts two souls sometimes two sets of teeth become strzygas",
            "Often described as having two hearts and two souls like upyrs",
            "Physically different people were potential strzyga candidates",
            "Redheads left-handed those with limp unibrow double set of teeth",
            "Gray mark on back also suspicious",
            "Religiously other like Lutherans in Catholic communities",
            "Chased from village if identified as strzyga",
            "Sometimes buried alive to prevent return",
            "Comes back from grave appears as owl",
            "Attacks travelers at night",
            "Drinks blood like vampire",
            "Many ideas reproduced in legends and ethnographic records of upyrs",
            "Often associated with witchcraft and dark magic"
        ],
        "habitat": "Graves, night sky as owl",
        "powers": ["Owl transformation", "Blood drinking", "Night flight", "Undead return"]
    },
    
    "Polewnik": {
        "description": "Field spirit, unbelievably short man with face full of grainy pimples, ears made of grain.",
        "behavior": "Wanders through fields, tricks people into getting lost. Strangles and murders people sleeping in fields, especially drunkards.",
        "legends": [
            "Face covered in grainy pimples",
            "Ears made of grain",
            "Leads strangers in wrong direction",
            "Hostile towards drunkards",
            "Strangles people sleeping in fields",
            "Field spirit from Slavic folklore",
            "Unbelievably short man with distinctive appearance",
            "Face full of grainy pimples",
            "Ears made of grain",
            "Wanders through fields",
            "Tricks people into getting lost",
            "Strangles and murders people sleeping in fields",
            "Especially dangerous to drunkards who sleep in fields",
            "Protector of crops but also dangerous to humans",
            "Can cause crops to fail if angered",
            "Sometimes helps farmers if treated with respect"
        ],
        "habitat": "Fields",
        "powers": ["Direction confusion", "Strangling", "Field camouflage", "Grain manipulation"]
    },
    
    "Werewolves": {
        "description": "Men who turn into wolves at night, especially during full moon. Roaring in darkness, brutal killers.",
        "behavior": "Can't control aggression and behavior. Transformation from wolf bite, curse, or black magic. Sometimes victims of magic seeking justice.",
        "legends": [
            "Transformation happens at full moon",
            "Wolf bite spreads curse",
            "Can be black magic curse for vengeance",
            "Brutally kills anyone in way",
            "No control over wolf form actions",
            "In Northwest Bulgaria believed werewolves devour celestial bodies slowly",
            "Allowing them to recover",
            "Only hole remains of moon",
            "To drive away demon people had to make loud noises",
            "Parallels to motif of wolf devouring celestial bodies",
            "Transformation often involuntary and uncontrollable",
            "Sometimes cursed by sorcerers or witches",
            "Can be born with werewolf curse",
            "Sometimes seek justice against those who wronged them",
            "In some tales can be cured by breaking the curse"
        ],
        "habitat": "Forests, villages at night",
        "powers": ["Wolf transformation", "Enhanced strength", "Bloodlust", "Pack hunting"]
    },
    
    "Vila": {
        "description": "South Slavic version of Rusalka. Beautiful young woman, lives on riverside or in lakes/river. Green long silky hair, fair skin, floral wreath.",
        "behavior": "Evil female water demon. Lures men with beauty and singing, drowns them. Can shapeshift into animals.",
        "legends": [
            "South Slavic equivalent of Rusalka",
            "Naked or in transparent silver robe",
            "Green hair like water grass",
            "Dances with men until they burn out and die",
            "Shapeshifts into snakes, wolves, swans, horses, falcons",
            "South Slavic fairy-like female spirits",
            "Beautiful young women with long silky hair",
            "Fair skin and floral wreath",
            "Lives on riverside or in lakes and rivers",
            "Evil female water demon in some traditions",
            "Lures men with beauty and singing then drowns them",
            "Can shapeshift into animals",
            "Sometimes benevolent and helpful to humans",
            "Often associated with mountains and forests as well as water",
            "Can heal the sick and foretell the future",
            "Sometimes fall in love with mortal men",
            "Can be offended by humans and take revenge",
            "Often dance in circles called kolo"
        ],
        "habitat": "Rivers, lakes, riverbanks",
        "powers": ["Beauty charm", "Singing", "Shapeshifting", "Dance of death"]
    },
    
    "Poroniec": {
        "description": "Embodiment of unclear force causing fear and unexpected death from violence. Souls of children who died before baptism.",
        "legends": [
            "Spirits of children who died before baptism",
            "Envious of life that never began for them",
            "Appear as infant birds late at night",
            "Attack children and pregnant women",
            "Eternally condemned souls",
            "Polish demonic creature from Slavic folklore",
            "Souls of children who died before baptism",
            "Envious of life that never began for them",
            "Causes fear and unexpected death from violence",
            "Embodiment of unclear force",
            "Often associated with sudden violent death",
            "Similar to other unbaptized child spirits like Drekavac",
            "Considered dangerous and malevolent",
            "Often blamed for unexplained deaths and accidents"
        ],
        "habitat": "Night, places of infant death",
        "powers": ["Fear induction", "Infant bird form", "Pregnant women attacks", "Child targeting"]
    },
    
    "Alkanost": {
        "description": "Bird with woman's face, very beautiful. Comes out only at night. Some versions consider demonic.",
        "behavior": "Sings beautifully to lure men and drive them mad. Lays eggs on beach, takes them under sea. When eggs hatch, thunderstorm arrives.",
        "legends": [
            "Bird with beautiful woman's face",
            "Sings so beautifully it drives men mad",
            "Omen of storms and sea destruction",
            "Eggs hatch into destructive sea forces",
            "Sometimes demonic - head of women who killed their children",
            "Lives in underworld with counterpart Sirin",
            "Alkonost lays eggs on beach and rolls them into sea",
            "When Alkonost's eggs hatch thunderstorm sets in",
            "Sea becomes so rough impossible to traverse",
            "Sister of other birds from Slavic mythology",
            "Comes from gods realm of Prawia/Prav",
            "Always considered helpful and kind",
            "Sirin comes from underworld and considered malevolent",
            "Both colorful birds with head of woman",
            "Alkonost from gods realm while Sirin from underworld",
            "Alkonost benevolent while Sirin maledictory"
        ],
        "habitat": "Sea coast, night sky",
        "powers": ["Beautiful singing", "Madness induction", "Storm omen", "Sea control"]
    },
    
    "Ala": {
        "description": "Female demon of bad weather in Bulgarian, Macedonian, and Serbian folklore. Leads hail-producing thunderclouds to destroy crops.",
        "behavior": "Extremely voracious, particularly likes to eat children. Sometimes tries to devour the Sun or Moon causing eclipses. Can assume various shapes.",
        "legends": [
            "Female demon of bad weather in Bulgarian Macedonian and Serbian folklore",
            "Main purpose is to lead hail-producing thunderclouds toward fields vineyards or orchards",
            "Destroy crops or loot and take them away",
            "Extremely voracious particularly likes to eat children",
            "Sometimes tries devouring the Sun or Moon causing eclipses",
            "Would mean end of world should they succeed",
            "When people encounter ala mental or physical health or even life in peril",
            "Her favor can be gained by approaching with respect and trust",
            "Being in good relationship with ala very beneficial",
            "Makes her favorites rich and saves their lives in times of trouble",
            "Appearance diversely and often vaguely described",
            "May look like black wind gigantic creature of indistinct form",
            "Huge-mouthed humanlike or snakelike monster dragoness or raven",
            "May assume various human or animal shapes",
            "Can even possess person's body",
            "Diversity of appearances due to ala being synthesis of Slavic demon of bad weather and pre-Slavic Balkan demon",
            "In folk tales with humanlike ala personality similar to Russian Baba Yaga",
            "Ale live in clouds or in lake spring hidden remote place forest inhospitable mountain cave or gigantic tree",
            "Usually hostile towards humans but have powerful enemies like dragons",
            "In Christianized tales St Elijah takes dragons' role",
            "Sometimes saint and dragons fight ale together",
            "Eagles regarded as defenders against ale chasing them away from fields",
            "Exclusive to Bulgarian Macedonian and Serb folklore",
            "Among North Slavs this witch was called Baba Yaga",
            "Baba Yaga imagined as woman of gigantic stature with big nose iron teeth and protruding chin",
            "Believed she ate children and her presence brought thunderstorms and cold weather",
            "Pre-Slavic Balkan source related to vlva female demons of bad weather of Romanians of Timok Valley",
            "Like ale led hail clouds over crops to ruin them and uprooted trees",
            "Greek female demon Lamia might have contributed to development of ala",
            "Just like ale she eats children and is called gluttonous",
            "In southern Serbia and North Macedonia lamnja derived from lamia is synonym for ala",
            "Bulgarian lamya remained distinct from ala but shares many similarities",
            "In Bulgaria farmers saw horrible ala with huge wings and sword-like thick tail in contours of dark cloud"
        ],
        "habitat": "Clouds, lakes, springs, remote places, forests, mountains, caves",
        "powers": ["Weather control", "Hail summoning", "Shape-shifting", "Possession"]
    },
    
    "Mavka": {
        "description": "Female spirit in Ukrainian folklore, soul of the forest. Long-haired temptress who lures men to their deaths.",
        "behavior": "Appears as beautiful young girl. Entices young men into woods and tickles them to death. No reflection in water, casts no shadow.",
        "legends": [
            "Type of female spirit in Ukrainian folklore and mythology",
            "Long-haired Soul of the Forest",
            "Typically depicted as temptress figure who lures men to their deaths",
            "Also called Nyavka in Ukrainian",
            "Terms derive from Proto-Slavic nav meaning the dead",
            "Spirits represented souls of girls who died unnatural tragic or premature deaths",
            "Particularly unchristened babies",
            "Often appear in form of beautiful young girls",
            "Entice and lure young men into woods",
            "Tickle them to death",
            "Have no reflection in water nor cast shadows",
            "In some accounts help farmers by looking after cattle and driving out wild animals",
            "Live in groups in forests mountain caves or sheds",
            "Decorated sheds with rugs",
            "Made thread of stolen flax and wove thin transparent cloth for clothes",
            "Loved flowers which they wore in hair",
            "In spring planted flowers in mountains to which they enticed young men",
            "On Pentecost known as Navka's Easter held games dances and orgies",
            "Demon accompanied them on flute or pipes",
            "To save unchristened baby's soul throw up kerchief during Pentecost",
            "Say their name and add I baptise you",
            "Rescued soul would go to heaven",
            "If soul lived up to seven years and did not go to heaven baby would turn into mavka",
            "Mavka different from other female spirits in that her evil is not intentional",
            "At sight of young man falls into trance and realizes actions too late",
            "Very beautiful young maiden with very long hair",
            "Those more often called Nyavka lived in Western Ukraine",
            "Mavkas lived in Central Ukraine had their backs",
            "Western Ukraine had more dangerous mountain rivers",
            "Looked like young women only from front",
            "From back could see all insides as they didn't have skin",
            "When running on grass it rocked under their feet",
            "Could be found in woods at crossroads or in fields",
            "Nice round face and beautiful tall stature",
            "Mavkas-boys had short red curly hair",
            "Mavkas-girls had long blond hair",
            "Often made friends with mermaids",
            "In some regions considered kind of mermaids or forest mermaids",
            "Took revenge with people for their early death",
            "Would misdirect people into swamps where they would drown",
            "Sometimes asked travelers to give them comb",
            "If got it would comb hair and go away otherwise could kill travelers",
            "Appeared on earth in springtime",
            "On Green holiday danced with frenzy near lakes and rivers",
            "On Mavkas' Easter turned into people and ate ordinary human food",
            "On Mermaids' week ran through fields shouting My mother gave birth to me and then she buried me unbaptized",
            "If someone baptizes mavka turns into angel and thanks benefactor by various favours",
            "Can only be baptized for seven years after death of child",
            "If in seven years baptism did not happen mavka will never become angel and remain demon forever",
            "Protection against mavkas garlic onion horseradish and lovage",
            "Wormwood could protect humans against these treacherous beauties",
            "Chuhayster hunted mavkas and saved people",
            "Funny humorous cheerful goblin with blue eyes covered with black or white hair",
            "Mavkas knowledgeable and endowed with magical abilities",
            "People treated them respectfully especially during Pentecost",
            "Brought them sacrificial bread and placed on fields hoping mavkas could contribute crops"
        ],
        "habitat": "Forests, mountain caves, fields, crossroads",
        "powers": ["Beauty charm", "Tickling death", "No reflection", "Forest magic"]
    },
    
    "Nocnitsa": {
        "description": "Female nightmare spirit in East Slavic folklore. Torments sleepers by sitting on their chest, causing nightmares and suffocation.",
        "behavior": "Most notably present in Russian Serbian and Slovak folklore. Torments children at night. Stone with hole in center offers protection.",
        "legends": [
            "Female nightmare spirit in East Slavic folklore",
            "Particularly Russian Serbian and Slovak folklore",
            "Torments sleepers especially children",
            "Sits on their chest causing nightmares",
            "Causes suffocation-like sensations akin to sleep paralysis",
            "Drains vital energy from victims",
            "Also goes by names Krisky or Plaksy",
            "Other names include kriksy plaksy plachky plaksivicy kriksy-varaksy kriksy-plaksy",
            "Also called night hag or night maiden",
            "In Russian and Slovak folklore torments children at night",
            "Stone with hole in center said to provide protection",
            "Often believed throughout Middle East to come into people's homes at night",
            "Would watch people while they sleep",
            "Causes terrifying nightmares and sleep disturbances",
            "Can be warded off with protective charms and stones",
            "Associated with sleep paralysis phenomenon",
            "Considered dangerous to children and vulnerable sleepers"
        ],
        "habitat": "Bedrooms, night time",
        "powers": ["Nightmare induction", "Sleep paralysis", "Chest sitting", "Energy draining"]
    },
    
    "Zirnitra": {
        "description": "Black dragon god of sorcery in Slavic mythology. Symbol of destructive force and magical power.",
        "behavior": "Associated with sorcery and magical abilities. Represents destructive force in Central and Eastern European Slavic regions.",
        "legends": [
            "Black dragon god of sorcery in Slavic mythology",
            "Symbol of destructive force",
            "Primary type dragons and beasts",
            "Region Central and Eastern Europe Slavic regions",
            "Often described as black dragon",
            "God of sorcery",
            "Serves as symbol of destructive force",
            "Associated with magical power and sorcery",
            "Considered powerful dragon deity",
            "Linked to dark magic and destructive forces",
            "Represents destructive force in Slavic mythology",
            "Connected to sorcery and magical practices"
        ],
        "habitat": "Mythical realms, associated with dark magic",
        "powers": ["Sorcery", "Destructive power", "Dragon abilities", "Magic"]
    },
    
    "Gamayun": {
        "description": "Prophetic bird of Slavic mythology. Speaks human language, tells fortunes and prophecies.",
        "legends": [
            "Prophetic bird that knows everything",
            "Speaks human language",
            "Tells fortunes and prophecies",
            "Symbol of wisdom and knowledge",
            "Associated with fate and destiny",
            "Prophetic bird alongside Sirin and Alkonost",
            "Knows everything about creation gods heroes humans",
            "Speaks human language to share wisdom",
            "Lives on island of Buyan in ocean",
            "Symbol of wisdom and divine knowledge",
            "Often depicted as bird with head of woman",
            "Can reveal secrets of the universe to those who deserve it",
            "Her prophecies are always accurate but often cryptic",
            "Considered one of the three prophetic birds of Slavic mythology"
        ],
        "habitat": "Mythical realms, appears to chosen ones",
        "powers": ["Prophecy", "Human speech", "Fortune telling", "Wisdom"]
    },
    
    "Sirin": {
        "description": "Paradise bird with beautiful voice. Lives in Iriy (paradise). Sometimes associated with happiness but also dangerous.",
        "legends": [
            "Lives in paradise (Iriy)",
            "Beautiful voice that can enchant",
            "Sometimes dangerous - can lead to madness",
            "Associated with happiness but also temptation",
            "Often depicted on grape trees",
            "Colorful bird with head of woman and sings beautiful songs",
            "Comes from underworld and considered malevolent",
            "Alkonost comes from gods realm of Prawia/Prav and always considered helpful and kind",
            "Sirin and Alkonost are both colorful birds with head of woman",
            "Sirin comes from underworld while Alkonost from gods realm",
            "Sirin considered maledictory while Alkonost benevolent",
            "Often depicted alongside Alkonost and Gamayun in Slavic folklore",
            "Represents temptation and danger despite beautiful appearance",
            "Her song can make listeners forget everything and follow her to death"
        ],
        "habitat": "Paradise (Iriy), magical gardens",
        "powers": ["Enchanting song", "Paradise dwelling", "Happiness or madness"]
    },
    
    "Solovey-Razboynik": {
        "description": "Robber nightingale, monster with human body and bird features. Whistle so powerful it can knock down trees and kill people.",
        "legends": [
            "Whistle can knock down trees from miles away",
            "Kills people with his powerful voice",
            "Lives in nests, blocks travel routes",
            "Defeated by Ilya Muromets in famous tale",
            "Half man, half bird monster",
            "Also called Nightingale the Robber or Solovey the Brigand",
            "Bylina also called The First Journey of Ilya Muromets",
            "One of most popular Russian epics recorded 132 times",
            "Monster Solovey had partial human and bird-like features",
            "Able to fly and lived in a nest",
            "Had human family and received drinks with his hands",
            "Lived in forest and sat in tree stunning strangers with powerful whistle",
            "When whistled: all grasses and meadows become entangled",
            "Azure flowers lose their petals",
            "All dark woods bend down to earth",
            "All people there lie dead",
            "Ilya Muromets survived whistle even though Nightingale leveled half forest",
            "Ilya shot down Nightingale with arrows to eye and temple",
            "Dragged defeated monster before Vladimir Prince of Kiev",
            "Vladimir wished to hear Nightingale whistle",
            "Creature claimed too wounded to whistle",
            "Requested wine to drink so wounds would disappear",
            "When whistled all Vladimir's palaces were destroyed and many lay dead",
            "Ilya took Nightingale into open field and cut off his head",
            "Legend discovered by Pavel Ivanovich Melnikov in 17th century handwritten collection",
            "Published in Nizhegorodskie gubernskie vedomosti in 1845 and 1847",
            "Ancient times where Nizhny Novgorod now stands lived famous Mordvin Skvorets",
            "Friend of another Mordvin Solovey connected with Ilya Muromets",
            "Nest on nine oak trees",
            "Also had terem (palace)",
            "Had sons and daughter bogatyrsha called perevozchitsa (ferrywoman)",
            "Called Odikhmantiev son, Rakhmanovich, Rakhmatovich",
            "Bird rahmanna represents complex image with traits of bird and human",
            "Some scholars connect to legends about Solomon",
            "Others see reflection of image of Sigurd",
            "Historical basis may be chronicle tale about robber Moguta",
            "Some interpret as metaphor of struggle between cults of Veles and Perun",
            "Later Christianity and paganism"
        ],
        "habitat": "Forests, nests in trees",
        "powers": ["Destructive whistle", "Tree destruction", "Death voice", "Flight"]
    },
    
    "Chuma": {
        "description": "Demon of plague and disease. Personification of deadly epidemics.",
        "legends": [
            "Embodiment of plague and disease",
            "Brings deadly epidemics to villages",
            "Feared during times of sickness",
            "Appears as old woman or shadow",
            "Cannot be stopped once released",
            "Čumas believed to live in far away land from where they set out to infect people",
            "Hate dirtiness and especially eager to infect dirty house",
            "If plague appeared in vicinity every house and occupants must be thoroughly cleaned",
            "Few ways to avoid Čuma during times of plague",
            "Disease could run rampant but people would clean their homes",
            "Grant offerings including basil and comb",
            "Scary and sad part of Slavic folklore",
            "Reminder of how strong and brave Slavic people are when they face problems",
            "In stories and legends about Chuma there are often heroes and women who bravely fought against plague",
            "Looked for cures and treatments to save their people",
            "Personification of deadly epidemics that could wipe out entire villages",
            "Often appears as terrifying old woman or shadowy figure",
            "Once released cannot be stopped until takes its toll",
            "Considered one of most feared supernatural beings",
            "Associated with death and suffering on massive scale",
            "Could be appeased through rituals and offerings",
            "Cleaning houses was believed to help prevent Čuma from entering",
            "Basil and comb were traditional protective offerings"
        ],
        "habitat": "Anywhere plague strikes",
        "powers": ["Disease spreading", "Plague manifestation", "Death induction", "Epidemic control"]
    },
    
    "Firebird": {
        "description": "Magical bird with glowing plumage. Feathers glow like fire. Symbol of hope and miraculous transformation.",
        "legends": [
            "Feathers glow brightly like fire",
            "Brings good fortune to capturer",
            "Hard to catch, always escapes",
            "Symbol of hope and transformation",
            "Appears in many Slavic fairy tales",
            "Described as having golden feathers while eyes like unto oriental crystal",
            "Large bird with majestic plumage glowing brightly emitting red orange and yellow light",
            "Like a bonfire just past turbulent flame",
            "Feathers do not cease glowing if removed",
            "One feather can light a large room if not concealed",
            "In later iconography usually form of smallish fire-colored falcon",
            "Complete with crest on head and tail feathers with glowing eyes",
            "Typical role is as object of difficult quest",
            "Quest initiated by finding lost tail feather",
            "Hero sets out to find and capture live bird",
            "Usually on bidding of father or king",
            "Firebird is marvel highly coveted",
            "Hero initially charmed by wonder of feather eventually blames it for troubles",
            "Firebird tales follow classical scheme of fairy tale",
            "Feather serves as premonition of hard journey",
            "Magical helpers met on way help in travel and capture of bird",
            "Returning from faraway land with prize",
            "Many versions as primarily told orally in beginning",
            "Has parallels in Iranian legends of magical birds",
            "Related to Brothers Grimm fairy tale about Golden Bird",
            "Related to Russian magical birds like Sirin"
        ],
        "habitat": "Magical gardens, distant lands",
        "powers": ["Glowing plumage", "Good fortune", "Flight", "Magical transformation"]
    },
    
    "Bauk": {
        "description": "Creature from Southern Slavic beliefs. Dangerous to people, looks to harm them. Lurks in dark abandoned places.",
        "behavior": "Spends time in dark abandoned houses or barns, waits for wanderers to walk in then eats them. Can be scared by light and loud noises.",
        "legends": [
            "Lurks in dark abandoned houses and barns",
            "Waits for wanderers then eats them",
            "Afraid of light and loud noises",
            "Southern Slavic origin",
            "Hides in shadows until victim approaches",
            "Can be scared away by light and loud noises",
            "Name comes from Serbian word meaning to scare",
            "Similar to other Slavic household spirits but more malevolent",
            "Often used to scare children from dangerous places"
        ],
        "habitat": "Abandoned houses, barns, dark places",
        "powers": ["Shadow hiding", "Ambush predation", "Fear of light"]
    },
    
    "Balachko": {
        "description": "Three-headed giant. Spits fire从 one head, freezing cold wind from another. Limited time for powers.",
        "behavior": "Can use fire and cold only for limited time. Once exhausted, becomes easy to kill. Russian Tzar managed to kill one when it kidnapped princess.",
        "legends": [
            "Three heads with different powers",
            "One head spits fire, another freezing wind",
            "Powers limited in duration",
            "Vulnerable when powers exhausted",
            "Kidnapped princess, killed by Russian Tzar"
        ],
        "habitat": "Unknown, likely mountains or remote areas",
        "powers": ["Fire breathing", "Freezing wind", "Giant strength", "Power limitation"]
    }
}

def get_monster_info(monster_name):
    """Get detailed information about a specific monster."""
    return MONSTERS_DB.get(monster_name, {
        "description": f"A creature from Slavic folklore known as {monster_name}.",
        "behavior": "A mysterious being with powers rooted in ancient Slavic beliefs.",
        "legends": [
            f"Stories of {monster_name} have been passed down through generations.",
            f"This creature represents the fears and wisdom of Slavic people."
        ],
        "habitat": "Various locations in Slavic lands",
        "powers": ["Ancient magic", "Supernatural abilities"]
    })

def get_all_monster_names():
    """Get list of all monster names in the database."""
    return list(MONSTERS_DB.keys())

def get_monsters_by_habitat(habitat_keyword):
    """Get monsters that match a habitat keyword."""
    matching = []
    for name, info in MONSTERS_DB.items():
        if habitat_keyword.lower() in info["habitat"].lower():
            matching.append(name)
    return matching

def get_rotated_legends(monster_name, cycle_number=0):
    """Get legends for a monster, rotated based on cycle number to ensure variety."""
    monster_info = get_monster_info(monster_name)
    legends = monster_info["legends"]
    
    if not legends:
        return []
    
    # Calculate rotation based on cycle number
    total_legends = len(legends)
    rotation_offset = (cycle_number * 3) % total_legends  # Rotate by 3 legends per cycle
    
    # Rotate the legends list
    rotated_legends = legends[rotation_offset:] + legends[:rotation_offset]
    
    # Return first 3-5 legends for the prompt
    return rotated_legends[:5]
